name: ohno-tests

on: [push]

jobs:
  OHNO:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install beef
      run: sudo apt install -y beef
    - name: brainfuck
      run: beef OHNO/ohno.bf

    - name: install cobol compiler
      run: sudo apt install -y gnucobol
    - name: compile cobol
      run: cobc -o ohno.cbl.out -x OHNO/ohno.cbl
    - name: cobol
      run: ./ohno.cbl.out

    - name: install java
      run: sudo apt install -y default-jre
    - name: compile java
      run: javac -d . OHNO/ohno.java
    - name: java
      run: java ohno

    - name: install python
      run: sudo apt install -y python
    - name: python
      run: python OHNO/ohno.py

    - name: install c compilers #(yes plural so we don't fight over clang vs gcc :)
      run: sudo apt install -y gcc clang
    - name: compile c
      run: |
        gcc -o ohno.gcc.out OHNO/ohno.c
        clang -o ohno.clang.out OHNO/ohno.c
    - name: c
      run: ./ohno.gcc.out
    - name: clang
      run: ./ohno.clang.out

    - name: install c++ compilers #(read above)
      run: sudo apt install -y clang g++
    - name: compile c++
      run: |
        g++ -o ohno.g++.out OHNO/ohno.cpp
        clang -o ohno.clang++.out OHNO/ohno.cpp
    #- name: g++
    #  run: ./ohno.g++.out        # FIX PLEASE ohno.cpp
    #- name: clang++
    #  run: ./ohno.clang++.out

    - name: install haskell compiler
      run: sudo apt install -y ghc
    - name: compile haskell
      run: ghc -no-keep-o-files -no-keep-hi-files -o ohno.hs.out OHNO/ohno.hs
    - name: haskell
      run: ./ohno.hs.out

    - name: install node
      run: sudo apt install -y nodejs
    - name: js
      run: node OHNO/ohno.js

    - name: install shells #(hi fish users)
      run: sudo apt install --ignore-missing -y bash fish ash zsh yash xonsh
    - name: sh
      run: |
        bash OHNO/ohno.sh
        fish OHNO/ohno.sh
        ash OHNO/ohno.sh
        zsh OHNO/ohno.sh
        yash OHNO/ohno.sh
        xonsh OHNO/ohno.sh

    - name: install rust
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        default: true
        override: true
    - name: compile rust
      run: rustc OHNO/ohno.rs -o OHNO/ohno-rs
    - name: run rust
      run: ./OHNO/ohno-rs

    - name: install go
      uses: actions/setup-go@v2.1.3
    - name: run golang
      run: ./OHNO/ohno.go
