name: ohno-tests

on: [push]

jobs:
  OHNO:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: explore OHNO
      run: cd OHNO

    - name: install beef
      run: apt install -y beef
    - name: brainfuck
      run: beef ohno.bf

    - name: install cobol compiler
      run: apt install -y gnucobol
    - name: compile cobol
      run: cobc -o ohno.cbl.out -x ohno.cbl
    - name: cobol
      run: ./ohno.cbl.out

    - name: install java
      run: apt install -y default-jre
    - name: compile java
      run: javac ohno.java
    - name: java
      run: java ohno

    - name: install python
      run: apt install -y python
    - name: python
      run: python ohno.py

    - name: install c compilers #(yes plural so we don't fight over clang vs gcc :)
      run: apt install -y gcc clang
    - name: compile c
      run: |
        gcc -o ohno.gcc.out ohno.c
        clang -o ohno.clang.out ohno.c
    - name: c
      run: ./ohno.gcc.out
    - name: clang
      run: ./ohno.clang.out

    - name: install c++ compilers #(read above)
      run: apt install -y clang g++
    - name: compile c++
      run: |
        g++ -o ohno.g++.out ohno.cpp
        clang -i ohno.clang++.out ohno.cpp
    - name: g++
      run: ./ohno.g++.out
    - name: clang++
      run: ./ohno.clang++.out

    - name: install haskell compiler
      run: apt install -y ghc
    - name: compile haskell
      run: ghc -no-keep-o-files -no-keep-hi-files -o ohno.hs.out ohno.hs
    - name: haskell
      run: ./ohno.hs.out

    - name: install node
      run: apt install -y nodejs
    - name: js
      run: node ohno.js

    - name: install shells #(hi fish users)
      run: apt install --ignore-missing -y bash fish ash zsh yash xonsh
    - name: sh
      run: |
        bash ohno.sh
        fish ohno.sh
        ash ohno.sh
        zsh ohno.sh
        yash ohno.sh
        xonsh ohno.sh
