name: PR Tests

on: [pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Install Android SDK
        run: sdkmanager "build-tools;30.0.1"

      - name: Add Android SDK to PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

      - name: Mark as executable
        run: chmod +x gradlew

      - name: Build mod jar
        run: ./gradlew buildDex

      - name: Upload built jar file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/chaos.jar